POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "name": "Alex",
  "email": "a@m.com",
  "password": "123456"
}

###
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
  "login": "a@m.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body.token); %}

###
#################################################
## Category
#################################################
###
POST http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "category",
  "prefix": "cat"
}

###
PUT http://localhost:8080/api/v1/category/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "category (update)",
  "description": "new description"
}

###
GET http://localhost:8080/api/v1/category/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###
#################################################
## Note
#################################################
###
POST http://localhost:8080/api/v1/note
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "The Second note",
  "description": "first note's words..."
}

###
PUT http://localhost:8080/api/v1/note/35
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "note",
  "categoryId": 2,
  "description": "updated description"
}

###
GET http://localhost:8080/api/v1/note/4
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8080/api/v1/note
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/api/v1/note/35/comment
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "content": "еще один коммент"
}


###
#################################################
## Tag
#################################################
###
POST http://localhost:8080/api/v1/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "warning"
}

###
PUT http://localhost:8080/api/v1/tag/37
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "error"
}

###
GET http://localhost:8080/api/v1/tag
Content-Type: application/json
Authorization: Bearer {{auth_token}}
